---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - config.ritsec.cloud
  resources:
  - discords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ritsec.cloud
  resources:
  - discords/finalizers
  verbs:
  - update
- apiGroups:
  - config.ritsec.cloud
  resources:
  - discords/status
  verbs:
  - get
  - patch
  - update
